[package]
name = "bd"
version = "0.1.0"
authors = ["Avery Wagar <awagar@cfchildren.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.4"
bus = "2.2.2"
